const adminSession = PizzariumAuth.getSession();
const adminOrders = [];
let activeFilter = 'all';
const statusNames = { new: 'New', confirmed: 'Confirmed', preparing: 'Preparing', out_for_delivery: 'Out for delivery', completed: 'Completed', cancelled: 'Cancelled' };
async function enforceAdminAccess() { if (!adminSession?.access_token) { location.replace('sign-in.html'); return; } const role = await PizzariumAuth.getUserRole(adminSession); if (!['admin', 'staff'].includes(role)) { alert('This page is only available to Pizzarium staff.'); location.replace('index.html'); return; } document.querySelector('#staffName').textContent = adminSession.user.user_metadata?.full_name || adminSession.user.email; loadOrders(); }
enforceAdminAccess();

function headers() { return { apikey: PizzariumAuth.key, Authorization: `Bearer ${adminSession.access_token}`, 'Content-Type': 'application/json' }; }
function rupees(value) { return `PKR ${Number(value || 0).toLocaleString()}`; }
function prettyDate(value) { return new Intl.DateTimeFormat('en-PK', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function filteredOrders() { return adminOrders.filter(order => activeFilter === 'all' || (activeFilter === 'active' ? ['confirmed', 'preparing', 'out_for_delivery'].includes(order.status) : order.status === activeFilter)); }
function renderOrders() { const list = document.querySelector('#ordersList'), orders = filteredOrders(); list.innerHTML = orders.length ? orders.map(order => `<article class="order-card"><div><div class="order-number">#${order.order_number || '—'}</div><small>${prettyDate(order.created_at)}</small></div><div class="order-customer"><h2>${escapeHtml(order.customer_name)}</h2><p>${escapeHtml(order.customer_phone)} · ${order.fulfillment_type === 'delivery' ? 'Delivery' : 'Pickup'}</p>${order.delivery_address ? `<p>${escapeHtml(order.delivery_address)}</p>` : ''}${order.notes ? `<p class="order-note">“${escapeHtml(order.notes)}”</p>` : ''}<div class="order-items">${(order.items || []).map(item => `<div class="order-item"><span>${escapeHtml(item.name)} · ${escapeHtml(item.size)} × ${item.quantity}</span><span>${rupees(item.line_total)}</span></div>`).join('')}</div></div><div class="order-meta"><div><strong class="order-total">${rupees(order.total)}</strong>${order.location_url ? `<a class="map-link" target="_blank" rel="noreferrer" href="${escapeHtml(order.location_url)}">Open delivery pin ↗</a>` : ''}</div><select data-order-id="${order.id}" aria-label="Change order status">${Object.entries(statusNames).map(([value, label]) => `<option value="${value}" ${value === order.status ? 'selected' : ''}>${label}</option>`).join('')}</select></div></article>`).join('') : '<div class="empty-orders">No orders found for this filter.</div>'; }
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]); }
function updateStats() { const today = new Date().toDateString(), todayOrders = adminOrders.filter(order => new Date(order.created_at).toDateString() === today); document.querySelector('#newCount').textContent = adminOrders.filter(order => order.status === 'new').length; document.querySelector('#progressCount').textContent = adminOrders.filter(order => ['confirmed', 'preparing', 'out_for_delivery'].includes(order.status)).length; document.querySelector('#completedCount').textContent = todayOrders.filter(order => order.status === 'completed').length; document.querySelector('#salesTotal').textContent = rupees(todayOrders.filter(order => order.status !== 'cancelled').reduce((sum, order) => sum + Number(order.total || 0), 0)); }
async function loadOrders() { const status = document.querySelector('#adminStatus'); status.textContent = 'Loading orders…'; try { const response = await fetch(`${PizzariumAuth.url}/rest/v1/orders?select=*&order=created_at.desc`, { headers: headers() }); if (!response.ok) throw new Error(await response.text()); adminOrders.splice(0, adminOrders.length, ...(await response.json())); updateStats(); renderOrders(); status.textContent = `${adminOrders.length} order${adminOrders.length === 1 ? '' : 's'} loaded`; } catch (error) { console.error(error); status.textContent = 'You do not have staff access to view orders.'; document.querySelector('#ordersList').innerHTML = '<div class="empty-orders">Staff access is required. Run the admin database setup, then assign your account as an admin.</div>'; } }
document.querySelector('#refreshOrders').addEventListener('click', loadOrders);
document.querySelector('#orderFilters').addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; activeFilter = button.dataset.filter; document.querySelectorAll('#orderFilters button').forEach(item => item.classList.toggle('active', item === button)); renderOrders(); });
document.querySelector('#ordersList').addEventListener('change', async event => { const select = event.target.closest('select[data-order-id]'); if (!select) return; select.disabled = true; try { const response = await fetch(`${PizzariumAuth.url}/rest/v1/orders?id=eq.${encodeURIComponent(select.dataset.orderId)}`, { method: 'PATCH', headers: { ...headers(), Prefer: 'return=minimal' }, body: JSON.stringify({ status: select.value }) }); if (!response.ok) throw new Error(await response.text()); const order = adminOrders.find(item => item.id === select.dataset.orderId); if (order) order.status = select.value; updateStats(); document.querySelector('#adminStatus').textContent = 'Order status updated'; } catch (error) { alert('Unable to update this order status.'); loadOrders(); } finally { select.disabled = false; } });
document.querySelector('#adminSignOut').addEventListener('click', event => { event.preventDefault(); PizzariumAuth.signOut(); });
