const PIZZARIUM_SUPABASE_URL = 'https://avtiuwvvkyzglvkrqpyg.supabase.co';
const PIZZARIUM_PUBLISHABLE_KEY = 'sb_publishable_AemE6eA9-KykfslVujMv9A_lAqo3UKn';
const sessionKey = 'pizzarium-auth-session';

function getSession() { try { return JSON.parse(localStorage.getItem(sessionKey)); } catch { return null; } }
function saveSession(session) { localStorage.setItem(sessionKey, JSON.stringify(session)); }
function clearSession() { localStorage.removeItem(sessionKey); }
async function authRequest(path, body) { const response = await fetch(`${PIZZARIUM_SUPABASE_URL}${path}`, { method: 'POST', headers: { apikey: PIZZARIUM_PUBLISHABLE_KEY, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.msg || result.message || result.error_description || 'Unable to complete your request.'); return result; }
async function signUp({ name, phone, email, password }) { const result = await authRequest('/auth/v1/signup', { email, password, data: { full_name: name, phone } }); if (result.access_token) saveSession(result); return result; }
async function signIn({ email, password }) { const result = await authRequest('/auth/v1/token?grant_type=password', { email, password }); saveSession(result); return result; }
async function requestPasswordReset(email, redirectTo) { return authRequest('/auth/v1/recover', { email, redirect_to: redirectTo }); }
async function getUserRole(session = getSession()) { if (!session?.access_token || !session?.user?.id) return null; try { const response = await fetch(`${PIZZARIUM_SUPABASE_URL}/rest/v1/profiles?id=eq.${encodeURIComponent(session.user.id)}&select=role`, { headers: { apikey: PIZZARIUM_PUBLISHABLE_KEY, Authorization: `Bearer ${session.access_token}` } }); if (!response.ok) return null; return (await response.json())[0]?.role || null; } catch { return null; } }
function signOut() { clearSession(); window.location.href = 'index.html'; }
function confirmSignOut() { return new Promise(resolve => { const popup = document.createElement('div'); popup.className = 'signout-popup'; popup.innerHTML = '<div class="signout-backdrop"></div><section class="signout-dialog" role="dialog" aria-modal="true" aria-labelledby="signoutTitle"><span class="signout-mark">✦</span><h2 id="signoutTitle">SIGN OUT?</h2><p>You will need to sign in again to add items or place an order.</p><div><button type="button" class="signout-cancel">Stay signed in</button><button type="button" class="signout-confirm">Sign out</button></div></section>'; document.body.append(popup); const close = result => { popup.remove(); resolve(result); }; popup.querySelector('.signout-backdrop').addEventListener('click', () => close(false)); popup.querySelector('.signout-cancel').addEventListener('click', () => close(false)); popup.querySelector('.signout-confirm').addEventListener('click', () => close(true)); }); }
async function addAdminLink(links, session) { try { const response = await fetch(`${PIZZARIUM_SUPABASE_URL}/rest/v1/profiles?id=eq.${encodeURIComponent(session.user.id)}&select=role`, { headers: { apikey: PIZZARIUM_PUBLISHABLE_KEY, Authorization: `Bearer ${session.access_token}` } }); const profile = (await response.json())[0]; if (profile && ['admin', 'staff'].includes(profile.role)) { const link = document.createElement('a'); link.className = 'auth-link admin-link'; link.href = 'admin.html'; link.textContent = 'Admin'; links.prepend(link); } } catch { /* Customers simply do not see the staff link. */ } }
function updateHeaderAccount() { const header = document.querySelector('.header'); if (!header || header.querySelector('.auth-links')) return; const session = getSession(), links = document.createElement('div'), cartLink = header.querySelector('.order-link'); if (cartLink && !session) cartLink.style.display = 'none'; links.className = 'auth-links'; if (session) { const signOutLink = document.createElement('a'); signOutLink.className = 'auth-link'; signOutLink.href = '#'; signOutLink.textContent = 'Sign out'; signOutLink.addEventListener('click', async event => { event.preventDefault(); if (await confirmSignOut()) signOut(); }); links.append(signOutLink); addAdminLink(links, session); } else { links.innerHTML = '<a class="auth-link" href="sign-in.html">Sign in</a><a class="auth-link auth-signup" href="sign-up.html">Sign up</a>'; } const menu = header.querySelector('.menu-toggle'); if (menu) header.insertBefore(links, menu); else header.append(links); }
window.PizzariumAuth = { getSession, signUp, signIn, signOut, requestPasswordReset, getUserRole, updateHeaderAccount, url: PIZZARIUM_SUPABASE_URL, key: PIZZARIUM_PUBLISHABLE_KEY };
document.addEventListener('DOMContentLoaded', () => { updateHeaderAccount(); const signInForm = document.querySelector('#signInForm'); if (signInForm && !document.querySelector('.forgot-password')) signInForm.insertAdjacentHTML('afterend', '<p class="auth-switch forgot-password"><a href="reset-request.html">Forgot password?</a></p>'); });
