const cartKey = 'pizzarium-cart';
const itemsEl = document.querySelector('#cartItems');
const emptyEl = document.querySelector('#emptyCart');
const subtotalEl = document.querySelector('#subtotal');
const addressField = document.querySelector('.address-field');
function readCart(){ return JSON.parse(localStorage.getItem(cartKey) || '[]'); }
function priceNumber(value){ const match = value.match(/(\d+)$/); return match ? Number(match[1]) : 0; }
function renderCart(){ const cart = readCart(); itemsEl.innerHTML = cart.map((item,index) => `<article class="cart-item"><div><h3>${item.name}</h3><p>${item.price}</p></div><div class="cart-side"><b>PKR ${priceNumber(item.price)*item.qty}</b><div class="qty-controls"><button data-action="minus" data-index="${index}">−</button><span>${item.qty}</span><button data-action="plus" data-index="${index}">+</button></div></div></article>`).join(''); emptyEl.classList.toggle('hidden',cart.length > 0); const total = cart.reduce((sum,item) => sum + priceNumber(item.price)*item.qty,0); subtotalEl.textContent = `PKR ${total.toLocaleString()}`; }
itemsEl.addEventListener('click',event=>{ const button=event.target.closest('button'); if(!button)return; const cart=readCart(), index=Number(button.dataset.index); cart[index].qty += button.dataset.action==='plus' ? 1 : -1; if(cart[index].qty<1)cart.splice(index,1); localStorage.setItem(cartKey,JSON.stringify(cart)); renderCart(); });
document.querySelector('#clearCart').addEventListener('click',()=>{localStorage.removeItem(cartKey);renderCart();});
document.querySelectorAll('input[name="fulfilment"]').forEach(input=>input.addEventListener('change',()=>{document.querySelectorAll('.fulfilment-option').forEach(option=>option.classList.toggle('active',option.querySelector('input').checked)); const delivery=input.value==='Delivery'; addressField.classList.toggle('hidden',!delivery); addressField.querySelector('textarea').required=delivery;}));
document.querySelector('#orderForm').addEventListener('submit',event=>{event.preventDefault();const cart=readCart();if(!cart.length){alert('Please add an item to your cart first.');return;}const data=new FormData(event.target), type=document.querySelector('input[name="fulfilment"]:checked').value;const lines=cart.map(item=>`• ${item.name} (${item.price}) × ${item.qty}`).join('\n');const total=cart.reduce((sum,item)=>sum+priceNumber(item.price)*item.qty,0);const message=`Hello Pizzarium!%0A%0A*New ${type} Order*%0A%0A${lines}%0A%0A*Total: PKR ${total}*%0A%0ACustomer: ${data.get('name')}%0APhone: ${data.get('phone')}${type==='Delivery'?`%0AAddress: ${data.get('address')}`:''}${data.get('notes')?`%0ANotes: ${data.get('notes')}`:''}%0A%0APlease confirm my order.`;window.open(`https://wa.me/923071001114?text=${encodeURIComponent(message)}`,'_blank','noopener');});
renderCart();
